/**
 * GET /api/export/markdown - Export specification as markdown
 */

import { NextRequest, NextResponse } from 'next/server';
import { sessionManager } from '@/lib/services/session-manager';
import type { Specification } from '@/lib/models/types';

function generateMarkdown(specification: Specification, sessionId: string): string {
  const { plainEnglishSummary, formalPRD } = specification;

  return `# Product Specification

**Session ID:** ${sessionId}
**Version:** ${specification.version}
**Last Updated:** ${new Date(specification.lastUpdated).toLocaleString()}

---

## Overview

${plainEnglishSummary.overview || 'No overview provided yet.'}

${plainEnglishSummary.estimatedComplexity ? `**Estimated Complexity:** ${plainEnglishSummary.estimatedComplexity}` : ''}

---

## Target Users

${plainEnglishSummary.targetUsers || 'Target users not specified yet.'}

---

## Key Features

${plainEnglishSummary.keyFeatures.length > 0
  ? plainEnglishSummary.keyFeatures.map((feature, i) => `${i + 1}. ${feature}`).join('\n')
  : 'No features defined yet.'}

---

## Integrations

${plainEnglishSummary.integrations.length > 0
  ? plainEnglishSummary.integrations.map((integration, i) => `- ${integration}`).join('\n')
  : 'No integrations specified.'}

---

## Formal Requirements

### Introduction

${formalPRD.introduction || 'Introduction will be generated as more information is gathered.'}

${Object.keys(formalPRD.glossary).length > 0 ? `
### Glossary

${Object.entries(formalPRD.glossary).map(([term, definition]) =>
  `**${term}:** ${definition}`
).join('\n\n')}
` : ''}

### Functional Requirements

${formalPRD.requirements.length > 0
  ? formalPRD.requirements.map((req, i) => `
#### ${req.id}: ${req.priority === 'must-have' ? '🔴 MUST-HAVE' : '🟡 NICE-TO-HAVE'}

**User Story:**
${req.userStory}

**Acceptance Criteria:**
${req.acceptanceCriteria.map(ac => `- ${ac}`).join('\n')}
`).join('\n---\n')
  : 'No requirements defined yet.'}

${formalPRD.nonFunctionalRequirements.length > 0 ? `
### Non-Functional Requirements

${formalPRD.nonFunctionalRequirements.map((nfr, i) => `
#### ${nfr.id}: ${nfr.category}

${nfr.description}
`).join('\n---\n')}
` : ''}

---

*Generated by Flowency Build Spec Wizard*
`;
}

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const sessionId = searchParams.get('sessionId');

    if (!sessionId) {
      return NextResponse.json(
        { success: false, error: 'Session ID is required' },
        { status: 400 }
      );
    }

    // Get session
    const session = await sessionManager.getSession(sessionId);
    if (!session) {
      return NextResponse.json(
        { success: false, error: 'Session not found' },
        { status: 404 }
      );
    }

    // Generate markdown
    const markdown = generateMarkdown(session.state.specification, sessionId);

    // Return as downloadable file
    return new NextResponse(markdown, {
      headers: {
        'Content-Type': 'text/markdown',
        'Content-Disposition': `attachment; filename="specification-${sessionId}.md"`,
      },
    });
  } catch (error) {
    console.error('Error generating markdown:', error);
    return NextResponse.json(
      { success: false, error: 'Failed to generate markdown' },
      { status: 500 }
    );
  }
}
